enum AuthActionTypes {
  AUTH_START = "AUTH_START",
  AUTH_SUCCESS = "AUTH_SUCCESS",
  AUTH_FAIL = "AUTH_FAIL",

  SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH",

  AUTH_LOGOUT = "AUTH_LOGOUT",
  AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS",
  AUTH_LOGOUT_FAIL = "AUTH_LOGOUT_FAIL",

  CHECK_VALID_SUCCESS = "CHECK_VALID_SUCCESS",

  REGISTER_START = "REGISTER_START",
  REGISTER_START_SUCCESS = "REGISTER_START_SUCCESS",
  REGISTER_START_FAIL = "REGISTER_START_FAIL"
}

export default AuthActionTypes;
